"use client";
import { useEffect } from "react";
import FeatherIconLoader from "./components/FeatherIconLoader";

import localFont from "next/font/local";
import "./globals.css";
import "./styles/bootstrap.min.css";
import "./styles/fonts.css";
import "./styles/slick.css";
import "./styles/style.css";
import "./styles/responsive.css";

import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    const timer = setTimeout(() => {
      feather.replace(); // Re-run feather.replace after a short delay
    }, 100); // Delay in milliseconds

    return () => clearTimeout(timer); // Clean up the timer
  }, []); // Re-run whenever categories change
  return (
    <html lang="en">
      <Head>
        <script src="/js/jquery-1.12.4.min.js" defer></script>
        <script src="/js/bootstrap.bundle.min.js" defer></script>
        <script src="/js/feather.min.js" defer></script>
        <script src="/js/slick.min.js" defer></script>
        <script src="/js/dobpicker.js" defer></script>
        <script src="/js/script.js" defer></script>
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <FeatherIconLoader />
        {children}
      </body>
    </html>
  );
}
